#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
# Enables management via the init script.
# Distributes requests using a round-robin algorithm.

# Install necessary packages and add repository
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get update
apt-get install -y haproxy=1.8.*

# Enable HAProxy to start at boot
echo "ENABLED=1" >> /etc/default/haproxy

# Backup original configuration and create new one
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

# Write new configuration
cat <<EOL > /etc/haproxy/haproxy.cfg
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 217081-web-01 3.83.253.53:80 check
    server 217081-web-02 100.26.163.202:80 check
EOL

# Start HAProxy service
service haproxy start

