#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown $USER:$USER /etc/haproxy/haproxy.cfg

echo "
frontend dietalchemy
    bind *:80
    mode http
    default_backend app

backend app
   balance roundrobin
   server 217081-web-01 3.83.253.53:80 check
   server 217081-web-02 100.26.163.202:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart 

