#!/usr/bin/env bash
# nginx running, and listening on port 80 of all the server’s active IPv4 IPs

apt-get update -y
# Update package lists

apt-get install -y nginx
# Enable nginx to start on boot.

sudo service nginx enable
# Start nginx service

sudo service nginx start

